apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-190311-t1tt-service
spec:
  selector:
    app: enterprise-system-190311-t1tt
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
